### ISSUE TITLE
should COMPRESSION_NONE be 3?

### ISSUE THREAD

**Issue by ch-yx** [MestreLion/mcworldlib#8]
in your code it is 0.
i m not sure but i think that it should be 3.

**Comment by MestreLion** [comment]
This is possibly related to issue #4 : up until then there was no COMPRESSION_NONE (either 3 or 0). This is a constant I made up just to have a "falsy" value for compression in a blank object . But MCA "specs" mention only two possible values, 1 for Gzip and 2 for Zlib, and in practice Minecraft only used Zlib in all it's chunks since then.

This possibly changed with the introduction of the so called "external chunks". Perhaps 0 (or 3) is now used to indicate the chunks data is in an external file.

McWorldLib was not yet updated to support this new feature

**Comment by MestreLion** [comment]
External MCC chunks are not yet supported, but I changed the `COMPRESSION_*`  "enum" handling to properly reflect the WIki. Now `COMPRESSION_NONE` is 3 and it's not an invalid value. The invalid value of 0 is now unnamed, and `RegionChunk`'s constructor by default uses 2 (`COMPRESSION_ZLIB`) instead of the invalid 0, as it's the only compression used by Minecraft client
